services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_dashboard_app_development

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db/my_dashboard_app_development
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails tailwindcss:build && (bundle exec rails tailwindcss:watch & bundle exec rails server -b 0.0.0.0)"

volumes:
  postgres_data:
  bundle_cache:
